name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Render CLI
      - name: Install Render CLI
        run: |
          # Download and install Render CLI
          curl -sSL https://render.com/download/render-cli | bash
          # Make sure render command is available
          render --version

      # Step 3: Check if RENDER_API_KEY is passed correctly
      - name: Check RENDER_API_KEY environment variable
        run: |
          echo "Rendering API Key: ${{ secrets.RENDER_API_KEY }}"  # This will print a masked version

      # Step 4: Deploy to Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Deploying to Render using service ID"
          render deploy --service-id "rnd_IWYXUM64yarOXcFnNDTupcAbKpFA"  # Replace with your actual Render service ID
