name: Deploy to Render

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install the Render CLI
      - name: Install Render CLI
        run: |
          curl -fsSL https://render.com/download/render-cli | bash

      # Step 3: Deploy to Render using the API key and service ID
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploy --service-id <rnd_IWYXUM64yarOXcFnNDTupcAbKpFA>
