name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js and Render CLI using npm
      - name: Install Render CLI
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | bash -  # Install Node.js
          apt-get install -y nodejs
          npm install -g @render/render-cli  # Install Render CLI globally
          render --version  # Verify if Render CLI was installed successfully

      # Step 3: Check if RENDER_API_KEY is passed correctly
      - name: Check RENDER_API_KEY environment variable
        run: |
          echo "Rendering API Key: ${{ secrets.RENDER_API_KEY }}"  # This will print a masked version

      # Step 4: Deploy to Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Deploying to Render using service ID"
          render deploy --service-id "rnd_IWYXUM64yarOXcFnNDTupcAbKpFA"  # Replace with your actual Render service ID
